### PR TITLE
feat: added fidis-serial

### PR DESCRIPTION
**Pull request by kjappelbaum**

### CODE REVIEW

**Comment by danieleongari** [comment]
Did they add already the need of specifying serial/parallel? My calculation are still running fine on 1 cpu only

**Comment by kjappelbaum** [comment]
They said they'll remove it after the summer maintenance.

**Comment by danieleongari** [comment]
Ok thanks, feel free to remove the old ones that might induce to misusage of our resources.

**Comment by danieleongari** [comment]
I close this PR to gather all the updates in the same PR: https://github.com/lsmo-epfl/aiida-lsmo-codes/pull/14

**Pull request closed without merging**
